// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type configShadow struct {
	LogLevel      *string          `json:"log-level"      toml:"log-level"      yaml:"log-level"`
	Width         *uint            `json:"width"          toml:"width"          yaml:"width"`
	Height        *uint            `json:"height"         toml:"height"         yaml:"height"`
	MaxIterations *uint64          `json:"max-iterations" toml:"max-iterations" yaml:"max-iterations"`
	Scale         *float64         `json:"scale"          toml:"scale"          yaml:"scale"`
	Center        *impl.Complex128 `json:"center"         toml:"center"         yaml:"center"`
	Exponent      *impl.Complex128 `json:"exponent"       toml:"exponent"       yaml:"exponent"`
	Z             *impl.Complex128 `json:"z"              toml:"z"              yaml:"z"`
	C             *impl.Complex128 `json:"c"              toml:"c"              yaml:"c"`
	Julia         *bool            `json:"julia"          toml:"julia"          yaml:"julia"`
	Palette       *string          `json:"palette"        toml:"palette"        yaml:"palette"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Width = uint(720)
	set("width", configulator.LayerDefault, "default tag")
	cfg.Height = uint(480)
	set("height", configulator.LayerDefault, "default tag")
	cfg.MaxIterations = uint64(1000)
	set("max-iterations", configulator.LayerDefault, "default tag")
	cfg.Scale = 1.0
	set("scale", configulator.LayerDefault, "default tag")
	{
		var slot impl.Complex128
		_ = slot.UnmarshalText([]byte("0"))
		v, _ := slot.Value()
		cfg.Center = v
		set("center", configulator.LayerDefault, "default tag")
	}
	{
		var slot impl.Complex128
		_ = slot.UnmarshalText([]byte("2"))
		v, _ := slot.Value()
		cfg.Exponent = v
		set("exponent", configulator.LayerDefault, "default tag")
	}
	{
		var slot impl.Complex128
		_ = slot.UnmarshalText([]byte("0"))
		v, _ := slot.Value()
		cfg.Z = v
		set("z", configulator.LayerDefault, "default tag")
	}
	{
		var slot impl.Complex128
		_ = slot.UnmarshalText([]byte("(-0.63+0.34i)"))
		v, _ := slot.Value()
		cfg.C = v
		set("c", configulator.LayerDefault, "default tag")
	}
	cfg.Julia = false
	set("julia", configulator.LayerDefault, "default tag")
	cfg.Palette = Palette("rainbow")
	set("palette", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Width != nil {
		cfg.Width = *s.Width
		set("width", configulator.LayerFile, file)
	}
	if s.Height != nil {
		cfg.Height = *s.Height
		set("height", configulator.LayerFile, file)
	}
	if s.MaxIterations != nil {
		cfg.MaxIterations = *s.MaxIterations
		set("max-iterations", configulator.LayerFile, file)
	}
	if s.Scale != nil {
		cfg.Scale = *s.Scale
		set("scale", configulator.LayerFile, file)
	}
	if s.Center != nil {
		v, ok := s.Center.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"1+2i\"",
				Path: "center",
			}
		}
		cfg.Center = v
		set("center", configulator.LayerFile, file)
	}
	if s.Exponent != nil {
		v, ok := s.Exponent.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"1+2i\"",
				Path: "exponent",
			}
		}
		cfg.Exponent = v
		set("exponent", configulator.LayerFile, file)
	}
	if s.Z != nil {
		v, ok := s.Z.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"1+2i\"",
				Path: "z",
			}
		}
		cfg.Z = v
		set("z", configulator.LayerFile, file)
	}
	if s.C != nil {
		v, ok := s.C.Value()
		if !ok {
			return &configulator.OpaqueSpellingError{
				Hint: "\"1+2i\"",
				Path: "c",
			}
		}
		cfg.C = v
		set("c", configulator.LayerFile, file)
	}
	if s.Julia != nil {
		cfg.Julia = *s.Julia
		set("julia", configulator.LayerFile, file)
	}
	if s.Palette != nil {
		cfg.Palette = Palette(*s.Palette)
		set("palette", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "width"); ok {
		p, err := strconv.ParseUint(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "width",
				Source: n,
				Value:  v,
			}
		}
		cfg.Width = uint(p)
		set("width", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "height"); ok {
		p, err := strconv.ParseUint(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "height",
				Source: n,
				Value:  v,
			}
		}
		cfg.Height = uint(p)
		set("height", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "max-iterations"); ok {
		p, err := strconv.ParseUint(v, 10, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "max-iterations",
				Source: n,
				Value:  v,
			}
		}
		cfg.MaxIterations = p
		set("max-iterations", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "scale"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "scale",
				Source: n,
				Value:  v,
			}
		}
		cfg.Scale = p
		set("scale", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "center"); ok {
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "center",
				Source: n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Center = sv
		set("center", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "exponent"); ok {
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "exponent",
				Source: n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Exponent = sv
		set("exponent", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "z"); ok {
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "z",
				Source: n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Z = sv
		set("z", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "c"); ok {
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "c",
				Source: n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.C = sv
		set("c", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "julia"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "julia",
				Source: n,
				Value:  v,
			}
		}
		cfg.Julia = p
		set("julia", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "palette"); ok {
		cfg.Palette = Palette(v)
		set("palette", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, _ *cpflag.Options) error {
	names := []string{
		"log-level",
		"width",
		"height",
		"max-iterations",
		"scale",
		"center",
		"exponent",
		"z",
		"c",
		"julia",
		"palette",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "log level: debug, info, warn or error")
	fs.Var(impl.NewUint(720), names[1], "initial window width")
	fs.Var(impl.NewUint(480), names[2], "initial window height")
	fs.Uint64(names[3], 1000, "maximum iterations per point")
	fs.Float64(names[4], 1.0, "initial zoom scale, smaller zooms in")
	fs.String(names[5], "0", "initial view center")
	fs.String(names[6], "2", "exponent in z = z^exponent + c")
	fs.String(names[7], "0", "starting z for the Mandelbrot set")
	fs.String(names[8], "(-0.63+0.34i)", "c for the Julia set")
	fs.Bool(names[9], false, "start in Julia set mode")
	fs.String(names[10], "rainbow", "color palette: rainbow or grayscale")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, _ *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "width"; fs.Changed(n) {
		v, err := fs.GetUint(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "width",
				Source: "--" + n,
			}
		}
		cfg.Width = v
		set("width", configulator.LayerCLI, "--"+n)
	}
	if n := "height"; fs.Changed(n) {
		v, err := fs.GetUint(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "height",
				Source: "--" + n,
			}
		}
		cfg.Height = v
		set("height", configulator.LayerCLI, "--"+n)
	}
	if n := "max-iterations"; fs.Changed(n) {
		v, err := fs.GetUint64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "max-iterations",
				Source: "--" + n,
			}
		}
		cfg.MaxIterations = v
		set("max-iterations", configulator.LayerCLI, "--"+n)
	}
	if n := "scale"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "scale",
				Source: "--" + n,
			}
		}
		cfg.Scale = v
		set("scale", configulator.LayerCLI, "--"+n)
	}
	if n := "center"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "center",
				Source: "--" + n,
			}
		}
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "center",
				Source: "--" + n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Center = sv
		set("center", configulator.LayerCLI, "--"+n)
	}
	if n := "exponent"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "exponent",
				Source: "--" + n,
			}
		}
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "exponent",
				Source: "--" + n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Exponent = sv
		set("exponent", configulator.LayerCLI, "--"+n)
	}
	if n := "z"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "z",
				Source: "--" + n,
			}
		}
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "z",
				Source: "--" + n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Z = sv
		set("z", configulator.LayerCLI, "--"+n)
	}
	if n := "c"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "c",
				Source: "--" + n,
			}
		}
		var slot impl.Complex128
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "c",
				Source: "--" + n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.C = sv
		set("c", configulator.LayerCLI, "--"+n)
	}
	if n := "julia"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "julia",
				Source: "--" + n,
			}
		}
		cfg.Julia = v
		set("julia", configulator.LayerCLI, "--"+n)
	}
	if n := "palette"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "palette",
				Source: "--" + n,
			}
		}
		cfg.Palette = Palette(v)
		set("palette", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "width":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError("width", v, err)
				}
				if raw > math.MaxUint {
					return configJSONError("width", v, fmt.Errorf("%d overflows uint", raw))
				}
				num := uint(raw)
				s.Width = &num
			default:
				return configJSONError("width", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "height":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError("height", v, err)
				}
				if raw > math.MaxUint {
					return configJSONError("height", v, fmt.Errorf("%d overflows uint", raw))
				}
				num := uint(raw)
				s.Height = &num
			default:
				return configJSONError("height", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "max-iterations":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Uint()
				if err != nil {
					return configJSONError("max-iterations", v, err)
				}
				s.MaxIterations = &num
			default:
				return configJSONError("max-iterations", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "scale":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError("scale", v, err)
				}
				s.Scale = &num
			default:
				return configJSONError("scale", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "center":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString, jsontext.KindNumber:
				var slot impl.Complex128
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return configJSONError("center", v, err)
				}
				s.Center = &slot
			default:
				return configJSONError("center", v, fmt.Errorf("expected a text scalar (e.g. \"1+2i\"), got %v", v.Kind()))
			}
		case "exponent":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString, jsontext.KindNumber:
				var slot impl.Complex128
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return configJSONError("exponent", v, err)
				}
				s.Exponent = &slot
			default:
				return configJSONError("exponent", v, fmt.Errorf("expected a text scalar (e.g. \"1+2i\"), got %v", v.Kind()))
			}
		case "z":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString, jsontext.KindNumber:
				var slot impl.Complex128
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return configJSONError("z", v, err)
				}
				s.Z = &slot
			default:
				return configJSONError("z", v, fmt.Errorf("expected a text scalar (e.g. \"1+2i\"), got %v", v.Kind()))
			}
		case "c":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString, jsontext.KindNumber:
				var slot impl.Complex128
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return configJSONError("c", v, err)
				}
				s.C = &slot
			default:
				return configJSONError("c", v, fmt.Errorf("expected a text scalar (e.g. \"1+2i\"), got %v", v.Kind()))
			}
		case "julia":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Julia = &b
			default:
				return configJSONError("julia", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "palette":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Palette = &str
			default:
				return configJSONError("palette", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "width = %v\n", c.Width)
	fmt.Fprintf(&b, "height = %v\n", c.Height)
	fmt.Fprintf(&b, "max-iterations = %v\n", c.MaxIterations)
	fmt.Fprintf(&b, "scale = %v\n", c.Scale)
	fmt.Fprintf(&b, "center = %v\n", c.Center)
	fmt.Fprintf(&b, "exponent = %v\n", c.Exponent)
	fmt.Fprintf(&b, "z = %v\n", c.Z)
	fmt.Fprintf(&b, "c = %v\n", c.C)
	fmt.Fprintf(&b, "julia = %v\n", c.Julia)
	fmt.Fprintf(&b, "palette = %v\n", c.Palette)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
